### ISSUE TITLE
Missing method "showInstallmentPlan"

### ISSUE THREAD

**Issue by nschoen** [ratepay/magento-module#6]
Hello,
in the modules's config.xml is the following definition:

``` xml
<adminhtml_block_html_before>
  <observers>
    <RatePAY_Ratepaypayment_model_observer>
      <class>RatePAY_Ratepaypayment_Model_Observer</class>
      <method>showInstallmentPlan</method>
    </RatePAY_Ratepaypayment_model_observer>
  </observers>
</adminhtml_block_html_before>
```

But the class RatePAY_Ratepaypayment_Model_Observer has no method showInstallmentPlan. That's why I received an error and had to comment out the XML-Tag.
Is this method needed?

**Comment by vlkrrhmlw** [comment]
Hello,

thx for this. We fixed this and relese a new version 3.1.1. today.
