### ISSUE TITLE
Not compatible with CE 1.9.2.2

### ISSUE THREAD

**Issue by ghost** [ratepay/magento-module#7]
Das Modul funktioniert nicht mit deaktiviertem "Admin routing compatibility mode". Betrifft die CE 1.9.2.2 sowie nach SUPEE-6788 bzw. APPSEC-1034 aktualisierte Installationen.
- http://magento.com/security/patches/supee-6788
- http://magento.com/security/patches/supee-6788-technical-details

**Comment by vlkrrhmlw** [comment]
Hallo,

uns ist dieser Umstand bereits bekannt und wir haben dies bereits in das nächste Feature Release eingeplant.
